// LVDS dataFmt 2 of the iwr1843_sar_lvds firmware (lvds stream format adc_sar_meta, directive core-24 Step 2).
//
// Synthetic captures from the firmware project's sar_synth.py, with sar_parse.py's output as the golden
// (tests/data/sar_fmt2/, regenerated by make_fixtures.py there). Each capture is replayed datagram by datagram
// through DCA1000Handler (configure_pipeline + ingest_packet, no socket) with save_adc_frames on, then:
//   - chirp_meta.csv must equal sar_parse's _meta.csv byte for byte,
//   - adc_data.bin must equal sar_parse's _adc.bin (per-chirp FNV-1a 64 hashes in manifest.json),
//   - the published frames' ChirpMetaFrame must say what the scenario built (validity, flags, lags, runs).
// Scenarios: clean (H 64, 56, 0), late record, lost datagram, run restart, DCA1000 restart. These are synthetic:
// the bench comparison on a real capture is core-24 Step 3.
#include "test_harness.hpp"
#include "dca_test_support.hpp"
#include "fake_transports.hpp"
#include "ADCCubeConverter.hpp"
#include "DCA1000Handler.hpp"
#include "Radar.hpp"
#include "RadarConfig.hpp"

#include <sys/stat.h>

#include <cstdio>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <map>

using cpsl::radar::ChirpMeta;
using cpsl::radar::ChirpMetaFrame;
using cpsl::radar::LvdsStreamFormat;
using nlohmann::json;

namespace {

const std::string kData = std::string(TEST_DATA_DIR) + "/sar_fmt2";

std::string read_file(const std::string& path) {
    std::ifstream f(path, std::ios::binary);
    return std::string((std::istreambuf_iterator<char>(f)), std::istreambuf_iterator<char>());
}

const json& manifest() {
    static const json m = json::parse(read_file(kData + "/manifest.json"));
    return m;
}

const json& scenario(const std::string& name) {
    for (const json& s : manifest().at("scenarios"))
        if (s.at("name") == name) return s;
    throw std::runtime_error("no scenario " + name);
}

// the datagrams of a SARCAP1 capture (8-byte magic, then u16 LE length + datagram)
std::vector<std::vector<uint8_t>> read_capture(const std::string& path) {
    const std::string d = read_file(path);
    std::vector<std::vector<uint8_t>> out;
    CHECK(d.compare(0, 8, "SARCAP1\n") == 0);
    size_t pos = 8;
    while (pos + 2 <= d.size()) {
        const size_t n = static_cast<uint8_t>(d[pos]) | (static_cast<size_t>(static_cast<uint8_t>(d[pos + 1])) << 8);
        pos += 2;
        if (pos + n > d.size()) break;
        out.emplace_back(d.begin() + static_cast<std::ptrdiff_t>(pos), d.begin() + static_cast<std::ptrdiff_t>(pos + n));
        pos += n;
    }
    return out;
}

std::string fnv1a64(const char* p, size_t n) {
    uint64_t h = 0xCBF29CE484222325ULL;
    for (size_t i = 0; i < n; i++) {
        h ^= static_cast<uint8_t>(p[i]);
        h *= 0x100000001B3ULL;
    }
    char buf[17];
    std::snprintf(buf, sizeof buf, "%016llx", static_cast<unsigned long long>(h));
    return buf;
}

// a system JSON for IWR1843_SAR + iwr1843_sar_lvds + the fixture cfg, DCA1000 on, saving into out_dir
std::string write_sar_system(const std::string& name, const std::string& cfg_file, const std::string& out_dir,
                             bool save) {
    setenv(SystemConfigReader::kBoardsDirEnv, (std::string(CONFIG_DIR) + "/boards").c_str(), 1);
    json j = json::parse(R"({
        "schema_version": 2, "board": "IWR1843_SAR", "firmware": "iwr1843_sar_lvds", "radar_cfg": "",
        "cli": { "port": "/dev/null-not-opened" },
        "dca1000": { "enabled": true, "fpga_ip": "127.0.0.1", "host_ip": "127.0.0.1", "cmd_port": 4096,
                     "data_port": 4098 },
        "output": { "dir": "", "save_adc_frames": true, "save_raw_lvds": false },
        "runtime": { "firmware_check": "off", "frame_queue_depth": 16 }
    })");
    j["radar_cfg"] = (!cfg_file.empty() && cfg_file[0] == '/') ? cfg_file : kData + "/" + cfg_file;
    j["output"]["dir"] = out_dir;
    j["output"]["save_adc_frames"] = save;
    const std::string path = dca_test::tmp_dir() + "/sar_" + name + ".json";
    std::ofstream(path) << j.dump(2);
    return path;
}

struct Replay {
    bool ok = false;
    std::vector<ChirpMetaFrame> frames;  // as published, in order
    std::vector<uint64_t> indices;
    std::vector<size_t> missing;
    DCA1000Handler::Stats stats;
    std::string csv;  // chirp_meta.csv
    std::string adc;  // adc_data.bin
    size_t chirp_adc_bytes = 0;
    size_t chirps_per_frame = 0;
};

// replay `datagrams` through a DCA1000Handler configured for `cfg_file`; every frame is taken as soon as it is
// published (no frame is overwritten)
Replay replay(const std::string& name, const std::string& cfg_file,
              const std::vector<std::vector<uint8_t>>& datagrams, const std::string& out_dir = "") {
    Replay r;
    const std::string out = out_dir.empty() ? dca_test::tmp_dir() + "/sar_out_" + name : out_dir;
    std::filesystem::remove_all(out);
    std::filesystem::create_directories(out);
    SystemConfigReader sys(write_sar_system(name, cfg_file, out, true));
    CHECK(sys.initialized);
    if (!sys.initialized) {
        std::cerr << "    " << sys.get_error() << std::endl;
        return r;
    }
    const cpsl::radar::BoardDescriptor& b = sys.getBoard();
    RadarConfigReader radar(sys.getRadarConfigPath(), b.cfg_dialect.rx_mask_fields, b.cfg_dialect.frame_period_field);
    DCA1000Handler h;
    CHECK(h.configure_pipeline(sys, radar));
    r.chirp_adc_bytes = 4 * radar.get_num_rx_antennas() * radar.get_samples_per_chirp();
    r.chirps_per_frame = radar.get_chirps_per_frame();
    DCA1000Handler::Cube cube;
    for (const std::vector<uint8_t>& d : datagrams) {
        h.ingest_packet(d.data(), static_cast<int>(d.size()));
        for (;;) {
            uint64_t index = 0;
            size_t missing = 0;
            std::chrono::steady_clock::time_point at;
            ChirpMetaFrame meta;
            if (!h.take_frame(cube, index, missing, at, std::chrono::steady_clock::time_point::min(), &meta)) break;
            r.frames.push_back(std::move(meta));
            r.indices.push_back(index);
            r.missing.push_back(missing);
        }
    }
    CHECK(h.stop());
    r.stats = h.get_stats();
    r.csv = read_file(out + "/chirp_meta.csv");
    r.adc = read_file(out + "/adc_data.bin");
    r.ok = true;
    return r;
}

// chirp_meta.csv vs the goldens' _meta.csv (concatenated, one header); adc_data.bin vs their per-chirp hashes
void check_against_goldens(const Replay& r, const json& sc) {
    std::string want_csv;
    std::vector<std::string> want_adc;
    for (const json& g : sc.at("goldens")) {
        std::string csv = read_file(kData + "/" + g.at("meta_csv").get<std::string>());
        if (!want_csv.empty()) csv = csv.substr(csv.find("\r\n") + 2);  // one header
        want_csv += csv;
        for (const json& h : g.at("adc_chirp_fnv1a64")) want_adc.push_back(h.get<std::string>());
    }
    CHECK_EQ(r.csv.size(), want_csv.size());
    CHECK(r.csv == want_csv);
    if (r.csv != want_csv) {
        // the first differing line, for the log
        size_t a = 0, line = 0;
        while (a < r.csv.size() && a < want_csv.size() && r.csv[a] == want_csv[a]) {
            if (r.csv[a] == '\n') line++;
            a++;
        }
        std::cerr << "    chirp_meta.csv differs at line " << line + 1 << ":\n      driver: "
                  << r.csv.substr(r.csv.rfind('\n', a) + 1, 140) << "\n      golden: "
                  << want_csv.substr(want_csv.rfind('\n', a) + 1, 140) << std::endl;
    }
    CHECK_EQ(r.adc.size(), want_adc.size() * r.chirp_adc_bytes);
    size_t bad = 0;
    for (size_t k = 0; k < want_adc.size() && (k + 1) * r.chirp_adc_bytes <= r.adc.size(); k++) {
        if (fnv1a64(r.adc.data() + k * r.chirp_adc_bytes, r.chirp_adc_bytes) != want_adc[k]) {
            if (bad == 0) std::cerr << "    adc_data.bin chirp " << k << " differs from sar_parse _adc.bin" << std::endl;
            bad++;
        }
    }
    CHECK_EQ(bad, size_t(0));
}

Replay run_scenario(const std::string& name) {
    const json& sc = scenario(name);
    const Replay r = replay(name, sc.at("cfg").get<std::string>(),
                            read_capture(kData + "/" + sc.at("capture").get<std::string>()));
    if (r.ok) check_against_goldens(r, sc);
    return r;
}

const ChirpMeta& chirp(const Replay& r, size_t k) { return r.frames.at(k / r.chirps_per_frame).chirps.at(k % r.chirps_per_frame); }

}  // namespace

TEST_CASE(cfg_geometry_per_header_rule) {
    // B = H + 4 * rx * samples + 64; H = 64 if rx * samples % 4 == 0, 56 otherwise, 0 with the header off
    struct Case {
        const char* cfg;
        size_t h, b;
    } cases[] = {{"sar_fmt2_h64.cfg", 64, 64 + 2048 + 64}, {"sar_fmt2_h56.cfg", 56, 56 + 2040 + 64},
                 {"sar_fmt2_h0.cfg", 0, 2048 + 64}};
    for (const Case& c : cases) {
        RadarConfigReader r(kData + "/" + c.cfg);
        CHECK(r.initialized);
        CHECK_EQ(r.get_lvds_data_fmt(), 2);
        // adc until the firmware's map says otherwise: bytes per frame as before core-24
        CHECK_EQ(r.get_bytes_per_frame(), size_t(4) * r.get_samples_per_chirp() * 8);
        r.set_lvds_stream_format(LvdsStreamFormat::adc_sar_meta);
        CHECK_EQ(r.get_chirp_header_bytes(), c.h);
        CHECK_EQ(r.get_chirp_packet_bytes(), c.b);
        CHECK_EQ(r.get_bytes_per_frame(), c.b * 8);
        // Tc 2000 us (480 + 1520), period 16.3 ms (sar_synth.make_cfg). The CLI realizes 16.3 ms in float32 as
        // 3259999 ticks of 5 ns, so Tb = 299.995 us, as sar_cfg_check.py computes it
        CHECK_EQ(r.get_chirp_cycle_ticks_10ns(), 200000u);
        CHECK_EQ(r.get_frame_period_ticks_5ns(), 3259999u);
        CHECK_NEAR(r.get_chirp_cycle_s(), 2000e-6, 1e-12);
        CHECK_NEAR(r.get_frame_blank_s(), 299.995e-6, 1e-12);
    }
    // RadarConfig resolves the format from the firmware descriptor
    const std::string out = dca_test::tmp_dir() + "/sar_out_geometry";
    std::filesystem::create_directories(out);
    auto rc = cpsl::radar::RadarConfig::load(write_sar_system("geometry", "sar_fmt2_h64.cfg", out, false));
    CHECK(static_cast<bool>(rc));
    if (!rc) {
        std::cerr << "    " << rc.status.message << std::endl;
        return;
    }
    CHECK(rc->frame_shape().lvds_format == LvdsStreamFormat::adc_sar_meta);
    CHECK_EQ(rc->frame_shape().chirp_packet_bytes, 2176u);
    CHECK_EQ(rc->frame_shape().bytes, uint64_t(2176) * 8);
}

TEST_CASE(converter_packet_path_skips_header_and_records) {
    // 2 rx x 4 samples x 3 chirps, H 64, B = 64 + 32 + 64; every ADC word is distinct, header/record bytes 0x7F
    const size_t R = 2, S = 4, C = 3, H = 64, B = H + 4 * R * S + 64;
    std::vector<uint8_t> frame(B * C, 0x7F);
    for (size_t c = 0; c < C; c++)
        for (size_t w = 0; w < 2 * R * S; w++) {
            const uint16_t v = static_cast<uint16_t>(1000 * c + w);
            frame[c * B + H + 2 * w] = static_cast<uint8_t>(v & 0xFF);
            frame[c * B + H + 2 * w + 1] = static_cast<uint8_t>(v >> 8);
        }
    for (auto iq : {cpsl::radar::IqOrder::q_first, cpsl::radar::IqOrder::i_first}) {
        ADCCubeConverter conv;
        conv.configure(R, S, C, cpsl::radar::LvdsLayout::two_lane_iq_pairs, iq);
        conv.configure_packets(B, H);
        ADCCubeConverter::ADCCube cube;
        conv.convert(frame, cube);
        std::vector<int16_t> file;
        conv.file_order(frame, file);
        CHECK_EQ(file.size(), 2 * R * S * C);
        // the packed converter on the frame with headers and records removed gives the same cube
        std::vector<uint8_t> packed;
        for (size_t c = 0; c < C; c++)
            packed.insert(packed.end(), frame.begin() + static_cast<std::ptrdiff_t>(c * B + H),
                          frame.begin() + static_cast<std::ptrdiff_t>(c * B + H + 4 * R * S));
        ADCCubeConverter plain;
        plain.configure(R, S, C, cpsl::radar::LvdsLayout::two_lane_iq_pairs, iq);
        ADCCubeConverter::ADCCube want;
        plain.convert(packed, want);
        std::vector<int16_t> want_file;
        plain.file_order(packed, want_file);
        CHECK(cube == want);
        CHECK(file == want_file);
        bool no_fill = true;
        for (int16_t v : file) no_fill = no_fill && v != 0x7F7F;
        CHECK(no_fill);
    }
}

TEST_CASE(clean_capture_matches_sar_parse) {
    for (const char* name : {"clean", "clean_h56", "clean_h0"}) {
        std::cout << "    scenario " << name << std::endl;
        const Replay r = run_scenario(name);
        if (!r.ok) continue;
        const size_t n = r.frames.size() * r.chirps_per_frame;
        CHECK_EQ(n, scenario(name).at("goldens")[0].at("chirps").get<size_t>());
        CHECK_EQ(r.stats.records_valid, uint64_t(n));
        CHECK_EQ(r.stats.records_invalid, uint64_t(0));
        CHECK_EQ(r.stats.records_other_run, uint64_t(0));
        CHECK_EQ(r.stats.assembler.incomplete_frames, 0u);
        for (size_t f = 0; f < r.frames.size(); f++) {
            CHECK_EQ(r.indices[f], uint64_t(f));
            CHECK(r.frames[f].run_known);
            CHECK_EQ(r.frames[f].run_idx, 1);
            for (const ChirpMeta& m : r.frames[f].chirps) {
                CHECK(m.record_valid && m.adc_complete && m.has_time && !m.time_interpolated);
                CHECK_EQ(m.global_chirp_idx, static_cast<uint32_t>(m.chirp));
            }
        }
    }
    // sar_synth's lag is 1: chirp 7 (saturated) is the last of frame 0, reported by chirp 8 = frame 1's chirp 0,
    // so frame 0 is published without it and frame 1 carries it in prev_tail_sat[1]
    const Replay r = run_scenario("clean");
    if (!r.ok) return;
    CHECK_EQ(chirp(r, 7).sat_slices_aligned, -1);
    CHECK_EQ(r.frames[1].prev_tail_sat[1], 5);
    CHECK_EQ(r.frames[1].prev_tail_sat[0], -1);
    CHECK_EQ(chirp(r, 3).sat_slices_aligned, 5);
    CHECK_EQ(chirp(r, 4).sat_slices_aligned, 0);
    CHECK_EQ(chirp(r, 0).sat_slices_aligned, 0);   // reported by chirp 1 (lag 1): clean
    CHECK_EQ(chirp(r, 0).sat_ref_lag, 0);
    CHECK((chirp(r, 0).flags & cpsl::radar::kSarFlagSatValid) == 0);  // the run's first record has no result
    // times: 2000 us in a frame, + 300 us at a boundary
    CHECK_NEAR(chirp(r, 7).t_s, 7 * 2000e-6, 1e-9);
    CHECK_NEAR(chirp(r, 8).t_s, 8 * 2000e-6 + 300e-6, 1e-9);  // the synthetic tsTicks use Tb = 300 us
}

TEST_CASE(late_record) {
    const Replay r = run_scenario("late_record");
    if (!r.ok) return;
    // LATE-flagged records stay valid and say so
    for (size_t k : {size_t(5), size_t(20)}) {
        CHECK(chirp(r, k).record_valid);
        CHECK((chirp(r, k).flags & cpsl::radar::kSarFlagLate) != 0);
    }
    CHECK((chirp(r, 6).flags & cpsl::radar::kSarFlagLate) == 0);
    // chirp 13's write missed packet 13 (its slot holds chirp 11's record): invalid, ADC kept, time interpolated
    // from chirp 12, its saturation result (for chirp 11) lost
    const ChirpMeta& m = chirp(r, 13);
    CHECK(!m.record_valid);
    CHECK(m.adc_complete);
    CHECK(m.has_time && m.time_interpolated);
    CHECK_NEAR(m.t_s, chirp(r, 12).t_s + 2000e-6, 1e-12);
    CHECK_EQ(m.global_chirp_idx, 0u);  // record fields are cleared when invalid
    CHECK_EQ(r.stats.records_invalid, uint64_t(1));
    CHECK_EQ(r.stats.records_valid, uint64_t(39));
    // lag 2 at an even frame's chirp 0 reports the previous frame's second-to-last chirp: chirp 16 -> chirp 14
    CHECK_EQ(chirp(r, 16).sat_ref_lag, 2);
    CHECK_EQ(r.frames[2].prev_tail_sat[0], 5 + 14 % 3);
    CHECK_EQ(r.frames[2].prev_tail_sat[1], 5 + 15 % 3);  // chirp 17 (lag 2) -> chirp 15
    CHECK_EQ(r.frames[1].prev_tail_sat[1], 5 + 7 % 3);   // odd frame: chirp 8 (lag 1) -> chirp 7
    CHECK_EQ(r.frames[1].prev_tail_sat[0], -1);          // chirp 6: never reported
    CHECK_EQ(chirp(r, 3).sat_slices_aligned, 5 + 3 % 3); // in-frame, lag 2 from chirp 5
}

TEST_CASE(lost_datagram) {
    const Replay r = run_scenario("lost_datagram");
    if (!r.ok) return;
    size_t adc_lost = 0, rec_lost = 0;
    for (const ChirpMetaFrame& f : r.frames)
        for (const ChirpMeta& m : f.chirps) {
            adc_lost += m.adc_complete ? 0 : 1;
            rec_lost += m.record_valid ? 0 : 1;
            if (!m.record_valid) CHECK(m.time_interpolated);
        }
    // the ADC-only datagram costs one chirp's ADC; the one over packet 17's record slot also covers the ends of
    // packets 17 and 18's ADC blocks (sar_parse marks the same three chirps, see the golden rows)
    CHECK_EQ(adc_lost, size_t(3));
    CHECK(!chirp(r, 10).adc_complete && chirp(r, 10).record_valid);
    CHECK(!chirp(r, 17).adc_complete && !chirp(r, 17).record_valid);
    CHECK(!chirp(r, 18).adc_complete && chirp(r, 18).record_valid);
    CHECK_EQ(rec_lost, size_t(1));
    CHECK_EQ(r.stats.assembler.incomplete_frames, 2u);  // the two holes are in different frames
    CHECK_EQ(r.frames.size(), size_t(5));               // nothing shifted, nothing skipped
}

TEST_CASE(run_restart_in_one_recording) {
    // sensorStop / sensorStart without re-arming the DCA1000: run 2's packets follow run 1's in the recording.
    // Their records carry another runIdx and their own chirp numbers: none validates, each counts as other run.
    const Replay r = run_scenario("run_restart");
    if (!r.ok) return;
    CHECK_EQ(r.frames.size(), size_t(7));
    CHECK_EQ(r.stats.records_valid, uint64_t(40));
    CHECK_EQ(r.stats.records_invalid, uint64_t(16));
    CHECK_EQ(r.stats.records_other_run, uint64_t(16));
    for (size_t k = 40; k < 56; k++) CHECK(!chirp(r, k).record_valid);
    CHECK_EQ(r.frames[6].run_idx, 1);
}

TEST_CASE(dca1000_restart_starts_a_new_run) {
    // recording B (run 2) starts with byte count 0: FrameAssembler resyncs, chirp numbers restart at 0 and the
    // decoder takes run 2 as the run
    const Replay r = run_scenario("dca_restart");
    if (!r.ok) return;
    CHECK_EQ(r.stats.assembler.resyncs, 1u);
    CHECK_EQ(r.frames.size(), size_t(6 + 3));
    CHECK_EQ(r.stats.records_valid, uint64_t(48 + 24));
    CHECK_EQ(r.stats.records_invalid, uint64_t(0));
    CHECK_EQ(r.frames[5].run_idx, 1);
    CHECK_EQ(r.frames[6].run_idx, 2);
    CHECK_EQ(r.frames[6].chirps[0].chirp, uint64_t(0));
    CHECK_EQ(r.indices[6], uint64_t(6));  // AdcFrame::index keeps increasing across the resync
    CHECK(!r.frames[6].chirps[0].time_interpolated);
    CHECK_NEAR(r.frames[6].chirps[0].t_s, 0.0, 1e-12);  // a new time origin
}

TEST_CASE(radar_api_publishes_chirp_meta) {
    // the public path: RadarConfig + Radar::open with a fake CLI and the clean capture in a replay source
    const std::string out = dca_test::tmp_dir() + "/sar_out_api";
    std::filesystem::remove_all(out);
    std::filesystem::create_directories(out);
    auto rc = cpsl::radar::RadarConfig::load(write_sar_system("api", "sar_fmt2_h64.cfg", out, false));
    CHECK(static_cast<bool>(rc));
    if (!rc) return;
    auto cli = std::make_shared<FakeCli>();
    auto src = std::make_shared<cpsl::radar::ReplayPacketSource>(read_capture(kData + "/clean.sarcap"));
    auto r = cpsl::radar::Radar::open(*rc, {cli, src});
    CHECK(static_cast<bool>(r));
    if (!r) {
        std::cerr << "    " << r.status.message << std::endl;
        return;
    }
    cpsl::radar::Radar& radar = **r;
    CHECK(static_cast<bool>(radar.configure()));
    CHECK(static_cast<bool>(radar.start()));
    cpsl::radar::AdcFrame f;
    size_t frames = 0;
    while (frames < 5 && radar.next_adc_frame(f, std::chrono::milliseconds(2000))) {
        CHECK_EQ(f.meta.chirps.size(), size_t(8));
        CHECK_EQ(f.shape.chirps, 8u);
        CHECK(f.shape.lvds_format == LvdsStreamFormat::adc_sar_meta);
        CHECK_EQ(f.data.size(), size_t(1));
        CHECK_EQ(f.data[0].size(), size_t(512));
        for (const ChirpMeta& m : f.meta.chirps) {
            CHECK(m.record_valid);
            CHECK_EQ(m.chirp, f.index * 8 + (&m - f.meta.chirps.data()));
        }
        frames++;
    }
    CHECK_EQ(frames, size_t(5));
    CHECK(static_cast<bool>(radar.stop()));
    const cpsl::radar::Stats s = radar.stats();
    CHECK_EQ(s.records_valid, uint64_t(40));
    CHECK_EQ(s.records_invalid, uint64_t(0));
}

// Bench tool, a no-op unless SAR_REPLAY_CAPTURE is set: replays a dca_capture.py SARCAP1 file through the driver and
// leaves adc_data.bin + chirp_meta.csv in SAR_REPLAY_OUT, for a diff against sar_parse.py's _adc.bin / _meta.csv.
// SAR_REPLAY_CFG overrides the cfg (default: the shipped SAR_2ms_fmt2.cfg).
TEST_CASE(replay_env_capture) {
    const char* cap = std::getenv("SAR_REPLAY_CAPTURE");
    const char* out = std::getenv("SAR_REPLAY_OUT");
    if (!cap || !*cap) return;
    CHECK(out != nullptr && *out);
    if (!out || !*out) return;
    const char* cfg = std::getenv("SAR_REPLAY_CFG");
    const std::string cfg_file = (cfg && *cfg) ? cfg
        : std::string(CONFIG_DIR) + "/radar/IWR1843/iwr1843_sar_lvds/SAR_2ms_fmt2.cfg";
    const std::vector<std::vector<uint8_t>> datagrams = read_capture(cap);
    CHECK(!datagrams.empty());
    const Replay r = replay("env", cfg_file, datagrams, out);
    CHECK(r.ok);
    std::cout << "    replayed " << datagrams.size() << " datagrams -> " << r.indices.size() << " frames, records_valid "
              << r.stats.records_valid << " invalid " << r.stats.records_invalid << " other_run "
              << r.stats.records_other_run << "; wrote " << out << "/adc_data.bin (" << r.adc.size() << " B), chirp_meta.csv ("
              << r.csv.size() << " B)" << std::endl;
}

TEST_MAIN()
